language: ruby
before_script:
  - psql -c 'create database my_database_test;' -U postgres
  
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > $CCTR
  - chmod +x $CCTR
  - $CCTR before-build
  
script:
  # setup the test database, including any seed data
  - bundle exec rake db:setup
  # insert here any other steps needed (load other sample data, etc) before starting tests 
  # run RSpec tests, and capture coverage
  - bundle exec rspec
  - $CCTR format-coverage --output coverage/codeclimate.$SUITE.json
after_script:
  # combine coverage from all suites, and upload to CodeClimate
  - $CCTR sum-coverage coverage/codeclimate.*.json | $CCTR upload-coverage
  - $CCTR after-build --exit-code $TRAVIS_TEST_RESULT

services:
  - postgresql
addons:
  postgresql: "10"
rvm:
 - 2.6.3
